apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "project-app.fullname" . }}-config
data:
  model-host: "http://model-service:8081"
  exampleValue: "{{ .Values.config.exampleValue }}"
  logLevel: "{{ .Values.config.logLevel }}"
